server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${foodhub.datasource.driver-class-name}
      url: jdbc:mysql://${foodhub.datasource.host}:${foodhub.datasource.port}/${foodhub.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${foodhub.datasource.username}
      password: ${foodhub.datasource.password}
  redis:
    host: ${foodhub.redis.host}
    port: ${foodhub.redis.port}
    password: ${foodhub.redis.password}
    database: ${foodhub.redis.database}

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.foodhub.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      foodhub:
        mapper: debug
        service: info
        controller: info

foodhub:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: foodhub
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    user-secret-key: itheima
    user-ttl: 7200000
    user-token-name: authentication
  alioss:
    endpoint: ${foodhub.alioss.endpoint}
    access-key-id: ${foodhub.alioss.access-key-id}
    access-key-secret: ${foodhub.alioss.access-key-secret}
    bucket-name: ${foodhub.alioss.bucket-name}
  wechat:
    appid: ${foodhub.wechat.appid}
    secret: ${foodhub.wechat.secret}
    mchid: ${foodhub.wechat.mchid}
    mchSerialNo: ${foodhub.wechat.mchSerialNo}
    privateKeyFilePath: ${foodhub.wechat.privateKeyFilePath}
    apiV3Key: ${foodhub.wechat.apiV3Key}
    weChatPayCertFilePath: ${foodhub.wechat.weChatPayCertFilePath}
    notifyUrl: ${foodhub.wechat.notifyUrl}
    refundNotifyUrl: ${foodhub.wechat.refundNotifyUrl}
  shop:
    address: 北京市海淀区上地十街10号
  baidu:
    ak: EFEEFFEFEFE